### ISSUE TITLE
The background image needs to be 50% taller

### ISSUE THREAD

**Issue by csbrown** [csbrown/NCWIT_eprogram#1]
For small screens, it's not big enough to take up the front page.

To reproduce: Use the "mobile view" option in the browser console on the main page.  The background gets "tiled" which is ugly.

**Comment by MargretP** [comment]
I used 'mobile view' on Chrome to look at it and also on my Android phone, but I couldn't reproduce the issue. Have you opened it on your phone?
Also, I just downloaded background.jpg, background_huge.jpg, and background_sm.jpg and opened them in Photoshop. It looks like the first two are the same size: 2246 x 5000, and even the background_sm is 2244 wide.
Can you give me the name of the image you had in mind?

**Comment by csbrown** [comment]
fixed.
