### ISSUE TITLE
Copy pasta the winners code/html for honorable mentions and rising stars

### ISSUE THREAD

**Issue by csbrown** [csbrown/NCWIT_eprogram#3]
This should look the same, it just needs to be copied and names changed.  Probably this can be abstracted into something nice to minimize duplicate code.

**Comment by MargretP** [comment]
Copying the winners code sounded so fool-proof, but I managed to get something wrong. Sorry about that. I need to revisit that again.

**Comment by MargretP** [comment]
Done.

![image](https://user-images.githubusercontent.com/3112868/161643236-bb8c4775-210c-4b2b-ade9-ddb0ff5ab1de.png)
