### ISSUE TITLE
Figure out the footer

### ISSUE THREAD

**Issue by csbrown** [csbrown/NCWIT_eprogram#4]
The old doc file has no footer.  Not sure if we'd like to thank our sponsors in the footer or what.  Possibly include NCWIT-site-footer info so ppl can learn more.

**Comment by MargretP** [comment]
When I think of a footer, I think of something that appears on every page of a printed program. Is that what you have in mind?

**Comment by csbrown** [comment]
Not sure what I had in mind.  I edited the stuff in the existing footer on the page.  Probably this is sufficient.  :)
